package types

type ColorValue string
type ColorName string
type StyleValue string
type StyleName string
type FontWeight string
type FontWeightValue string

const (
	White      ColorName = "white"
	Yellow     ColorName = "yellow"
	Blue       ColorName = "blue"
	Red        ColorName = "red"
	Green      ColorName = "green"
	Black      ColorName = "black"
	Brown      ColorName = "brown"
	Azure      ColorName = "azure"
	Ivory      ColorName = "ivory"
	Teal       ColorName = "teal"
	Silver     ColorName = "silver"
	Purple     ColorName = "purple"
	NavyBlue   ColorName = "navy blue"
	PeaGreen   ColorName = "pea green"
	Gray       ColorName = "gray"
	Orange     ColorName = "orange"
	Maroon     ColorName = "maroon"
	Charcoal   ColorName = "charcoal"
	Aquamarine ColorName = "aquamarine"
	Coral      ColorName = "coral"
	Fuchsia    ColorName = "fuchsia"
	Wheat      ColorName = "wheat"
	Lime       ColorName = "lime"
	Crimson    ColorName = "crimson"
	Khaki      ColorName = "khaki"
	HotPink    ColorName = "hot pink"
	Magenta    ColorName = "magenta"
	Olden      ColorName = "olden"
	Plum       ColorName = "plum"
	Olive      ColorName = "olive"
	Cyan       ColorName = "cyan"
)

const (
	ColorWhite      ColorValue = "\033[97m"
	ColorYellow     ColorValue = "\033[93m"
	ColorBlue       ColorValue = "\033[94m"
	ColorRed        ColorValue = "\033[91m"
	ColorGreen      ColorValue = "\033[92m"
	ColorBlack      ColorValue = "\033[30m"
	ColorBrown      ColorValue = "\033[33m"
	ColorAzure      ColorValue = "\033[36m"
	ColorIvory      ColorValue = "\033[97m"
	ColorTeal       ColorValue = "\033[36m"
	ColorSilver     ColorValue = "\033[37m"
	ColorPurple     ColorValue = "\033[35m"
	ColorNavyBlue   ColorValue = "\033[34m"
	ColorPeaGreen   ColorValue = "\033[92m"
	ColorGray       ColorValue = "\033[90m"
	ColorOrange     ColorValue = "\033[33m"
	ColorMaroon     ColorValue = "\033[35m"
	ColorCharcoal   ColorValue = "\033[90m"
	ColorAquamarine ColorValue = "\033[36m"
	ColorCoral      ColorValue = "\033[91m"
	ColorFuchsia    ColorValue = "\033[95m"
	ColorWheat      ColorValue = "\033[93m"
	ColorLime       ColorValue = "\033[32m"
	ColorCrimson    ColorValue = "\033[91m"
	ColorKhaki      ColorValue = "\033[93m"
	ColorHotPink    ColorValue = "\033[95m"
	ColorMagenta    ColorValue = "\033[95m"
	ColorOlden      ColorValue = "\033[94m"
	ColorPlum       ColorValue = "\033[38;5;96m"
	ColorOlive      ColorValue = "\033[38;5;58m"
	ColorCyan       ColorValue = "\033[96m"
	ColorReset      ColorValue = "\033[0m"
)

const (
	BackgroundWhite      ColorValue = "\033[107m"
	BackgroundReset      ColorValue = "\033[49m"
	BackgroundYellow     ColorValue = "\033[43m"
	BackgroundBlue       ColorValue = "\033[44m"
	BackgroundRed        ColorValue = "\033[41m"
	BackgroundGreen      ColorValue = "\033[42m"
	BackgroundBlack      ColorValue = "\033[40m"
	BackgroundBrown      ColorValue = "\033[48;5;94m"
	BackgroundAzure      ColorValue = "\033[48;5;39m"
	BackgroundIvory      ColorValue = "\033[48;5;230m"
	BackgroundTeal       ColorValue = "\033[48;5;30m"
	BackgroundSilver     ColorValue = "\033[48;5;252m"
	BackgroundPurple     ColorValue = "\033[48;5;99m"
	BackgroundNavyBlue   ColorValue = "\033[48;5;17m"
	BackgroundPeaGreen   ColorValue = "\033[48;5;40m"
	BackgroundGray       ColorValue = "\033[48;5;242m"
	BackgroundOrange     ColorValue = "\033[48;5;208m"
	BackgroundMaroon     ColorValue = "\033[48;5;124m"
	BackgroundCharcoal   ColorValue = "\033[48;5;232m"
	BackgroundAquamarine ColorValue = "\033[48;5;122m"
	BackgroundCoral      ColorValue = "\033[48;5;203m"
	BackgroundFuchsia    ColorValue = "\033[48;5;201m"
	BackgroundWheat      ColorValue = "\033[48;5;229m"
	BackgroundLime       ColorValue = "\033[48;5;46m"
	BackgroundCrimson    ColorValue = "\033[48;5;203m"
	BackgroundKhaki      ColorValue = "\033[48;5;228m"
	BackgroundHotPink    ColorValue = "\033[48;5;205m"
	BackgroundMagenta    ColorValue = "\033[48;5;201m"
	BackgroundOlden      ColorValue = "\033[48;5;221m"
	BackgroundPlum       ColorValue = "\033[48;5;96m"
	BackgroundOlive      ColorValue = "\033[48;5;58m"
	BackgroundCyan       ColorValue = "\033[48;5;14m"
)

const (
	StyleReset     = "\033[0m"
	StyleBold      = "\033[1m"
	StyleItalic    = "\033[3m"
	StyleUnderline = "\033[4m"
	StyleReverse   = "\033[7m"
	StyleStrike    = "\033[9m"
)
const (
	Reset     = "reset"
	Bold      = "bold"
	Italic    = "italic"
	Underline = "underline"
	Reverse   = "reverse"
	Strike    = "strike"
)

const (
	FontWeightBoldText           FontWeightValue = "\033[1m"
	FontWeightFaintText          FontWeightValue = "\033[2m"
	FontWeightItalicText         FontWeightValue = "\033[3m"
	FontWeightUnderlineText      FontWeightValue = "\033[4m"
	FontWeightBlinkText          FontWeightValue = "\033[5m"
	FontWeightInverseText        FontWeightValue = "\033[7m"
	FontWeightConcealText        FontWeightValue = "\033[8m"
	FontWeightStrikethroughtText FontWeightValue = "\033[9m"
)
const (
	BoldText           FontWeight = "bold"
	FaintText          FontWeight = "faint"
	ItalicText         FontWeight = "italic"
	UnderlineText      FontWeight = "underline"
	BlinkText          FontWeight = "blink"
	InverseText        FontWeight = "inverse"
	ConcealText        FontWeight = "conceal"
	StrikethroughtText FontWeight = "strikethrought"
)
